project/accounts/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup', SignUp.as_view(), name='signup'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.mixins import LoginRequiredMixin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('django.contrib.flatpages.urls')),
    path("accounts/", include("allauth.urls")),
    path('news/', include('simpleapp.urls')),
]

project/simpleapp/urls.py
from django.urls import path
from .views import NewssList, NewsDetail, NewsCreate, NewsUpdate, NewsDelete

urlpatterns = [
   path('', NewssList.as_view(), name='news_list'),
   path('<int:pk>', NewsDetail.as_view()),
   path('search/', NewssList.as_view(template_name='search.html')),
   path('create/', NewsCreate.as_view(), name='news_create'),
   path('<int:pk>/update/', NewsUpdate.as_view(), name='news_update'),
   path('<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
   ]

project/accounts/models.py
from django.db import models

# Create your models here.

project/simpleapp/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator
from django.urls import reverse


class News(models.Model):
    name = models.CharField(
        max_length=128,
        unique=True,
    )
    text = models.TextField()
    amount_of_pages = models.IntegerField(
        validators=[MinValueValidator(0)],
    )

    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='posts'
    )
    date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return f'{self.name.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])


class Category(models.Model):

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()

project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

class CustomSignupForm(SignupForm):
    def save(self, request):
        user = super().save(request)
        kazualy = Group.objects.get(name="kazualy")
        user.groups.add(kazualy)
        return user

project/simpleapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import News

class NewsForm(forms.ModelForm):
   class Meta:
       model = News
       fields = [
           'name',
           'text',
           'category',
           'amount_of_pages',
           'date'
       ]

   def clean(self):
       cleaned_data = super().clean()
       text = cleaned_data.get("text")
       if text is not None and len(text) < 20:
           raise ValidationError({
               "text": "Текст не может быть менее 20 символов."
           })
       name = cleaned_data.get("name")
       if name == text:
           raise ValidationError(
               "Текст статьи не должен быть идентичен названию."
           )

       return cleaned_data

project/accounts/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from .forms import SignUpForm


class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = '/accounts/login'
    template_name = 'registration/signup.html'

project/simpleapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import News
from .filters import NewsFilter
from .forms import NewsForm

class NewssList(ListView):
    model = News
    ordering = '-date'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = NewsFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context



class NewsDetail(DetailView):
    model = News
    text = News.text
    template_name = 'post.html'
    context_object_name = 'post'

class NewsCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    raise_exception = True
    form_class = NewsForm
    model = News
    template_name = 'news_edit.html'
    success_url = reverse_lazy('news_list')

class NewsUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    raise_exception = True
    form_class = NewsForm
    model = News
    template_name = 'news_edit.html'
    success_url = reverse_lazy('news_list')

class NewsDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    raise_exception = True
    model = News
    template_name = 'news_delete.html'
    success_url = reverse_lazy('news_list')

project/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить новость "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
Хотите
<a href='http://127.0.0.1:8000/news/{{post.id}}/update'>изменить</a>
или
<a href='http://127.0.0.1:8000/news/{{post.id}}/delete'>удалить</a>
?
<h1>{{ post.name|censor }}</h1>
<hr>
{{ post.date|date:'d.M.Y' }}
{{ post.date|time:'H:i' }}
(Категория:{{ post.category.name }})
<hr>
{{ post.text|censor }}
{% endblock content %}

project/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все публикации</h1>
<a href='http://127.0.0.1:8000/news/search'>Перейти к поиску?</a>
<hr>
    {% if perms.simpleapp.add_product %}
    <a href="{% url 'news_create' %}">Добавить статью</a>
    {% endif %}
   {% if posts %}
       <table>
           <tr>
               <td>ID</td>
               <td>Название</td>
               <td>Текст</td>
               <td>Категория</td>
               <td>Количество страниц</td>
               <td>Дата и время публикации</td>
               {% if perms.simpleapp.change_news or perms.simpleapp.delete_news %}
                <td>Действия</td>
                {% endif %}
           </tr>
           {% for post in posts.all %}
           <tr>
               <td><a href='http://127.0.0.1:8000/news/{{post.id}}'>{{ post.id }}</a></td>
               <td>{{ post.name|censor }}</td>
               <td>{{ post.text|censor|truncatechars:20 }}</td>
               <td>{{ post.category.name }}</td>
               <td>{{ post.amount_of_pages }}</td>
               <td>{{ post.date|date:'d.M.Y' }} {{ post.date|time:'H:i' }}</td>
               <td>
               {% if perms.simpleapp.change_news %}
                    <a href="{% url 'news_update' pk=post.id %}">Изменить</a>
               {% endif %}
               {% if perms.simpleapp.delete_product %}
                    <a href="{% url 'news_delete' post.id %}">Удалить</a>
               {% endif %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Публикаций нет!</h2>
   {% endif %}
    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

project/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}

{% block content %}
   <h1>Все публикации</h1>
    <form action="" method="get">
       {{ filterset.form.as_p }} Формат ввода даты: ГГГГ-ММ-ДД
        <hr>
       <input type="submit" value="Найти" />
    </form>
   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>ID</td>
               <td>Название</td>
               <td>Текст</td>
               <td>Категория</td>
               <td>Количество страниц</td>
               <td>Дата и время публикации</td>
           </tr>
           {% for post in posts.all %}
           <tr>
               <td><a href='http://127.0.0.1:8000/news/{{post.id}}'>{{ post.id }}</a></td>
               <td>{{ post.name|censor }}</td>
               <td>{{ post.text|censor|truncatechars:20 }}</td>
               <td>{{ post.category.name }}</td>
               <td>{{ post.amount_of_pages }}</td>
               <td>{{ post.date|date:'d.M.Y' }} {{ post.date|time:'H:i' }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Публикаций нет!</h2>
   {% endif %}
    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}